#pragma once

#define MOTOR_OVERHEAD 0
#define JS_DERIVATIVE 1
#define LOSS_OF_CONTROL_AUTHORITY 2
#define VELOCITY_DEVIATION 3
#define COLLISION_SPEED 4
#define IS_CLOSE_TO_OBSTACLE 5
#define RP_RATE_DEVIATION 6