dynamic: true
modify_parameters: false
only_update_on_measurements: false
saving_factor: 1
max_risk: 0.01
spam_states: false
no_delay: true

# parameters converting measurements to states. Max is the lowest value that gives the worst case state
measurement_conversion:
  max_yaw_moment: 0.25
  max_turbulence: 0.03
  min_turbulence: 0.002
  max_tilt: 0.1
  min_tilt: 0.03
  max_number_of_filtered_points: 6
  motor_max: 1949
  motor_min: 1700
  filtered_point_lowpass_factor: 0

# Risk evaluation parameters:
risk:
  motor_saturation:
    constant: 0.3
    scale: 0.1
  turbulence:
    constant: 0.2
    scale: 0.1
  breaking_distance:
    constant: 0
    scale: 0.4
  damage: #scaled by height
    constant: 0.1
    scale: 0.3
  total: 
    damage_to_drone: 0.8
    loss_of_mission: 0.2

cost_function_parameters:
  target_cost: 5
  non_target_cost: 1
  acceleration_cost: 0.5
  parameter_change_cost: 0
  parameter_change_delay_factor: 0.15