max_risk: 0.005

# parameters converting measurements to states. Max is the lowest value that gives the worst case state
measurement_conversion:
  max_yaw_moment: 1 #TODO!
  max_turbulence: 0.006
  max_tilt: 0.2
  max_number_of_filtered_points: 10
  motor_max: 1949
  motor_min: 1600

# Risk evaluation parameters:
risk:
  motor_saturation:
    constant: 0.4
    scale: 0.2
  turbulence:
    constant: 0.2
    scale: 0.2
  unobservable_obs:
    constant: 0.05
    scale: 0.2
  breaking_distance:
    constant: 0.05
    scale: 0.2
  damage: #scaled by height
    constant: 0.1
    scale: 0.4
  total: 
    damage_to_drone: 0.8
    loss_of_mission: 0.2

cost_function_parameters:
  target_cost: 5
  non_target_cost: 1
  acceleration_cost: 0.6
  parameter_change_cost: 0.5